### ISSUE TITLE
Viết lại bản SDS 

### ISSUE THREAD

**Issue by Tuanhoang2302** [Tuanhoang2302/cnpm-project#22]

**Comment by NguyenThiThanhBao** [comment]
sds phải sửa một số hình vẽ thôi đúng không

**Comment by Tuanhoang2302** [comment]
k hẳn, phải sửa chi tiết lại chứ

**Comment by VuThiDiu** [comment]
thế giờ cần sửa nữa ko

**Comment by Tuanhoang2302** [comment]
à có đang sửa lại

**Comment by Tuanhoang2302** [comment]
mọi người tìm lại template cho cái bản sds srs để làm cho chuẩn nhé
