### ISSUE TITLE
Làm bản thiết kế chi tiết cho game 2

### ISSUE THREAD

**Issue by Tuanhoang2302** [Tuanhoang2302/cnpm-project#7]
Giờ chúng ta bắt đầu làm game 2. 
Trước khi làm game mình cần mọi người làm bản tóm tắt chi tiết về các màn chơi trong game 2, cụ thể game có 6 màn thì chỉ ra mỗi màn có những object gì, chức năng game cho mỗi màn và **MỖI MÀN** gồm có các state gì từ lúc bắt đầu cho tới lúc kết thức. Khi hoàn thành mọi người commit file và báo vào đây để mình xem và biết

**Comment by VuThiDiu** [comment]
ok1111111111111111111111111111111

**Comment by VuThiDiu** [comment]
ak mà game  có 6 màn nhé

**Comment by Tuanhoang2302** [comment]
sr nhầm :))

**Comment by NguyenThiThanhBao** [comment]
ok!
